# Generated by Django 3.1 on 2020-12-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expendetures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expendeture',
            name='typeOfExpendeture',
        ),
        migrations.AddField(
            model_name='expendeture',
            name='expendetureType',
            field=models.CharField(choices=[('SP', 'Scheduled Payment'), ('OOP', 'One-Off Payment')], default='OOP', max_length=3),
        ),
    ]
