# Generated by Django 3.1 on 2020-12-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expendetures', '0002_auto_20201222_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expendeture',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='expendeture',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
