# Generated by Django 3.1 on 2020-12-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expendetures', '0003_auto_20201222_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expendeture',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='expendeture',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
